# Generated by Django 3.0.5 on 2021-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_yamdbuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
